apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: symfony-demo-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: symfony-demo-app
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 5  # Maximum number of pods
  targetCPUUtilizationPercentage: 70