apiVersion: batch/v1
kind: Job
metadata:
  name: "flyway-{{ .Values.app.name }}"
  namespace: {{ .Values.app.namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec: 
  backoffLimit: 6
  template:
    spec:
      containers:
      - name: flyway
        image: "{{ .Values.image.flyway_repository }}:{{ .Values.image.flyway_tag }}"
        command: ["flyway"]
        args: [
          "migrate", 
          "-url=jdbc:mysql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.database }}", 
          "-user={{ .Values.db.flywayUser }}", 
          "-password={{ .Values.db.flywayPassword }}", 
          "-locations=filesystem:/flyway/sql/"
          ]
        env:
        - name: FLYWAY_URL
          value: "jdbc:mysql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}"
        - name: FLYWAY_USER
          value: "{{ .Values.db.flywayUser }}"
        - name: FLYWAY_PASSWORD
          value: "{{ .Values.db.flywayPassword }}"
      restartPolicy: OnFailure
    