apiVersion: batch/v1
kind: Job
metadata:
  name: "init-{{ .Values.app.name }}"
  namespace: {{ .Values.app.namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec: 
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: flyway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
        - |
          php bin/console doctrine:schema:create && \
          yes | php bin/console doctrine:fixtures:load
        env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      restartPolicy: OnFailure
    