apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- with .Values.podLabels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- with .Values.podLabels }}
    {{ toYaml . | indent 4 }}
    {{- end }}